### ISSUE TITLE
almost working... some API issue?

### ISSUE THREAD

**Issue by bbrendon** [latenighttales/alcali#156]
I think I'm close. I can't get the minions to show up. I'm not quite sure where my issue is. I have a feeling its related to the external_auth configuration?

Thanks.

In the GUI I see:
```
Salt WebSocket | OK
-- | --
jobs | 22
events | 106
schedules | 0
```

```
# In the master config...
external_auth:
  rest:
    ^url: http://127.0.0.1:8071/api/token/verify/
    admin:
      - .*
      - '@runner'
      - '@wheel'


# curl --insecure  https://localhost:8070
{"return": "Welcome", "clients": ["local", "local_async", "local_batch", "local_subset", "runner", "runner_async", "ssh", "wheel", "wheel_async"]}


# /opt/alcali/venv/bin/gunicorn config.wsgi:application -b 0.0.0.0:8071 -w 3
[2020-02-07 17:03:22 -0800] [22025] [INFO] Starting gunicorn 20.0.4
[2020-02-07 17:03:22 -0800] [22025] [INFO] Listening at: http://0.0.0.0:8071 (22025)
[2020-02-07 17:03:22 -0800] [22025] [INFO] Using worker: sync
[2020-02-07 17:03:22 -0800] [22028] [INFO] Booting worker with pid: 22028
[2020-02-07 17:03:22 -0800] [22029] [INFO] Booting worker with pid: 22029
[2020-02-07 17:03:22 -0800] [22030] [INFO] Booting worker with pid: 22030
[2020-02-07 17:04:10 -0800] [22025] [CRITICAL] WORKER TIMEOUT (pid:22028)


root@magnolia:/var/log/salt# cat api
2020-02-07 17:17:19,306 [cherrypy.error   :219 ][ERROR   ][24575] [07/Feb/2020:17:17:19] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1056)
```

**Comment by anitakrueger** [comment]
I have the same issue. I've got everything working I think, but no minions show up in my configuration. I'm using the `rest` authentication as well and I can actually see that the salt master is making a rest call to the api in the salt-master logs:
```
 salt-master[17842]: [DEBUG   ] Requesting URL http://127.0.0.1:5000/api/token/verify/ using POST method
```

I can also see alcali getting data from the salt-api for `/events` for example:
```
salt-api[19214]: [INFO    ] 127.0.0.1 - - [11/Feb/2020:15:10:51] "GET /events HTTP/1.1" 200 - "" "python-requests/2.22.0"
```

I'm not sure where the disconnect is :(

**Comment by mattLLVW** [comment]
Hey @bbrendon thanks for trying Alcali.

Have you seen [this](https://alcali.dev/troubleshooting/) section of the documentation?

According to the traceback, it looks like a cherrypy issue. What version are you using? Salt doesn't seems to play nice with all version IIRC.

Could you also provide master logs in debug ?
If Alcali is trying to authenticate, it should show up in the master's logs.

**Comment by mattLLVW** [comment]
Hey @anitakrueger , it could be a different problem so could you please create another issue? thanks!

**Comment by anitakrueger** [comment]
@mattLLVW I can do that. I have a sneaky feeling it is because I'm running salt 2019.2.3 on centos7 with Python2.7 and alcali is running on Python3.6. Could that be the issue?

**Comment by mattLLVW** [comment]
@anitakrueger i don't think it is, Alcali is tested against a salt 2018.3.4 Python 2.7 in the v2018.3.X version, so it should be fine.

**Comment by anitakrueger** [comment]
Ah ok. My next question would have been about logs for alcali. Been trying to find some, but all I see is a bit of output in journal (I'm starting gunicorn via systemd).
I'll turn up salt-master and salt-api to debug and see if I can see something there.

**Comment by mattLLVW** [comment]
@anitakrueger please create another issue.

**Comment by anitakrueger** [comment]
@mattLLVW not necessary it seems. I read through old github issues and found that I need to refresh the keys and then the minions and of course that worked, silly me.
I might open another issue to add this to the documentation...

**Comment by mattLLVW** [comment]
@anitakrueger great! It's in the [walkthrough](https://alcali.dev/walkthrough/) and kind of in the [minion view](https://alcali.dev/views/minions/) but yes, this behaviour should be more explicit. I would gladly accept a PR for this!

**Comment by bbrendon** [comment]
I played with it a bit more but didn't seem to make any progress. 

debian package : python3-cherrypy3                    8.9.1-2 


master log items that looked interesting...
```
2020-02-11 21:26:15,118 [salt.utils.http  :244 ][DEBUG   ][9885] Using backend: tornado
2020-02-11 21:26:15,265 [salt.utils.http  :618 ][DEBUG   ][9885] Response Status Code: 200
2020-02-11 21:26:15,267 [salt.loaded.int.auth.rest:64  ][DEBUG   ][9885] eauth REST call returned 200: {'body': '{"bbrendon":null}', 'status': 200, 'dict': {'bbrendon': None}}
2020-02-11 21:26:15,322 [salt.utils.lazy  :107 ][DEBUG   ][9885] Could not LazyLoad rest.groups: 'rest.groups' is not available.
2020-02-11 21:26:15,324 [salt.utils.lazy  :104 ][DEBUG   ][9885] LazyLoaded localfs.mk_token
2020-02-11 21:26:15,359 [salt.utils.lazy  :104 ][DEBUG   ][9889] LazyLoaded localfs.get_token
```

**Comment by bbrendon** [comment]
Also, why would I use the alcali auth vs the rest auth?

**Comment by mattLLVW** [comment]
@bbrendon what are the rights for the user bbrendon in the external_auth setting of the master?


> external_auth:
>   rest:
>     ^url: http://127.0.0.1:8071/api/token/verify/
>     admin:
>       - .*
>       - '@runner'
>       - '@wheel'

It looks like you're using the user bbrendon to login in the salt-api.

For Alcali to add minions, the user configured in the external_auth setting of the master must be able to run `pillar.items` and `grain.items`.


> why would I use the alcali auth vs the rest auth?

the alcali auth use a custom auth module (so it's a bit troublesome to install) to authenticate users **but**  the master does not need to be able to talk to alcali.

On the other hand the rest auth is easier to use **but** password are validated using and endpoint on Alcali so the master must be able to talk to Alcali and you must ensure that Alcali is running in https so that passwords does not transit in clear.

**Comment by bbrendon** [comment]
Okay. The login name to alcali and the username in the master file is now the same. This is the log I get when logging in. I'm not seeing anything different. https://pastebin.com/mRAKgAJ6

**Comment by bbrendon** [comment]
I might have found something. Restarting only salt-api gets and error.

```
2020-02-14 15:51:46,133 [salt.utils.decorators.jinja:31  ][DEBUG   ][28108] Marking 'union' as a jinja filter
2020-02-14 15:51:46,133 [salt.utils.decorators.jinja:31  ][DEBUG   ][28108] Marking 'intersect' as a jinja filter
2020-02-14 15:51:46,134 [salt.utils.decorators.jinja:31  ][DEBUG   ][28108] Marking 'difference' as a jinja filter
2020-02-14 15:51:46,134 [salt.utils.decorators.jinja:31  ][DEBUG   ][28108] Marking 'symmetric_difference' as a jinja filter
2020-02-14 15:51:46,191 [salt.client.netapi:75  ][INFO    ][28108] Starting rest_cherrypy.start netapi module
2020-02-14 15:51:46,198 [salt.utils.process:457 ][DEBUG   ][28108] Started 'RunNetapi' with pid 28210
2020-02-14 15:51:46,199 [salt.utils.process:518 ][DEBUG   ][28108] Process Manager starting!
2020-02-14 15:51:46,202 [salt.utils.lazy  :104 ][DEBUG   ][28210] LazyLoaded rest_cherrypy.start
2020-02-14 15:51:46,270 [salt.utils.event :326 ][DEBUG   ][28210] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
2020-02-14 15:51:46,271 [salt.utils.event :327 ][DEBUG   ][28210] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
2020-02-14 15:51:46,273 [cherrypy.error   :219 ][INFO    ][28210] [14/Feb/2020:15:51:46] ENGINE Listening for SIGTERM.
2020-02-14 15:51:46,274 [cherrypy.error   :219 ][INFO    ][28210] [14/Feb/2020:15:51:46] ENGINE Listening for SIGHUP.
2020-02-14 15:51:46,275 [cherrypy.error   :219 ][INFO    ][28210] [14/Feb/2020:15:51:46] ENGINE Listening for SIGUSR1.
2020-02-14 15:51:46,275 [cherrypy.error   :219 ][INFO    ][28210] [14/Feb/2020:15:51:46] ENGINE Bus STARTING
2020-02-14 15:51:46,276 [py.warnings      :110 ][WARNING ][28210] CherryPy Checker:
'log_file' is obsolete. Use 'log.error_file' instead.
section: [saltopts]


2020-02-14 15:51:46,277 [cherrypy.error   :219 ][INFO    ][28210] [14/Feb/2020:15:51:46] ENGINE Started monitor thread '_TimeoutMonitor'.
2020-02-14 15:51:46,278 [cherrypy.error   :219 ][INFO    ][28210] [14/Feb/2020:15:51:46] ENGINE Started monitor thread 'Autoreloader'.
2020-02-14 15:51:46,396 [cherrypy.error   :219 ][INFO    ][28210] [14/Feb/2020:15:51:46] ENGINE Serving on https://0.0.0.0:8070
2020-02-14 15:51:46,397 [cherrypy.error   :219 ][INFO    ][28210] [14/Feb/2020:15:51:46] ENGINE Bus STARTED
2020-02-14 15:51:46,404 [cherrypy.error   :219 ][ERROR   ][28210] [14/Feb/2020:15:51:46] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2021, in start
    self.tick()
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/__init__.py", line 2090, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/python3/dist-packages/cherrypy/wsgiserver/ssl_builtin.py", line 67, in wrap
    server_side=True)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error




```

**Comment by bbrendon** [comment]
I disabled SSL which removes the error `OSError: [Errno 0] Error`. But I still haven't gotten it to work. Is there a way to figure out what's causing :
```
[2020-02-18 15:12:48 -0800] [10986] [CRITICAL] WORKER TIMEOUT (pid:12643)
```
?

**Comment by mattLLVW** [comment]
@bbrendon it's not an alcali issue, it's a salt-api configuration issue.

Like i said, in the troubleshooting section: First make sure that your salt-api is correctly configured by using pam auth and curl.

**Comment by bbrendon** [comment]
It seems to work....?

```
# curl -sSk http://localhost:8070/login \
> -H 'Accept: application/x-yaml' \
> -d username=bbrendon \
> -d password=xxxx \
> -d eauth=pam
return:
- eauth: pam
  expire: 1582217992.894191
  perms:
  - .*
  - '@wheel'
  - '@runner'
  - '@jobs'
  start: 1582174792.8941903
  token: 272b1b7b1e116232efe050d70722acfebd7bac31
  user: bbrendon
#

```

**Comment by mattLLVW** [comment]
Hey @bbrendon you're right it looks like your salt-api is working correctly.
could you try that same curl command but swap `pam` for `rest` and **use the token** found in the [users view](https://alcali.dev/views/users/) as a  password?

**Comment by bbrendon** [comment]
```
curl -sSk http://localhost:8070/login \
> -H 'Accept: application/x-yaml' \
>  -d username=bbrendon \
>  -d password=<token from gui> \
>  -d eauth=rest
return:
- eauth: rest
  expire: 1582986990.1732278
  perms:
  - .*
  - '@runner'
  - '@wheel'
  - '@jobs'
  start: 1582943790.1732275
  token: <new token>
  user: bbrendon
$

curl -sSk http://localhost:8070 \
     -H 'Accept: application/x-yaml' \
     -H 'X-Auth-Token: <new token>'\
     -d client=local \
    -d tgt='*' \
    -d fun=test.ping

```

...That returns true/false with all minions listed.

**Comment by shaidar** [comment]
I'm having a similar issue where I don't see any minions in the alcali dashboard and noticed worker timeouts as reported above. I know alcali is communicating with the salt-api as in the alcali console in the cli, I can run tasks on minion and receive results. I also know that it's talking to the db as it lists the number of jobs and events. Just missing the minions (tried deleting one from the salt-key on the salt-master and adding it again, but that didn't help) and no detailed jobs are listed other than `loading items`. Appreciate any help as I'm no longer sure what else to verify/check.

**Comment by mattLLVW** [comment]
@shaidar are your keys present in the keys view?
have you tried refreshing keys?( the fab button on the bottom right in the key view).
have you tried refreshing minions?( the fab button on the bottom right in the minions view).

**Comment by shaidar** [comment]
@mattLLVW That was it. Thinks for pointing me in the right direction
