### ISSUE TITLE
Auth-ldap doesn't work with Gunicorn

### ISSUE THREAD

**Issue by valentin2105** [latenighttales/alcali#275]
**Describe the bug**
Hello,

I try to setup LDAP using the formula, in version `3000.1.0`. 
I have installed the lib like that :
```
su alcali
cd /opt/alcali/code
pip install --user alcali[ldap]
```

When I launch `alcali runserver` it work, but using systemd gunigorn from the formula, it throw errors : 

```
alcali[4634]: [2020-12-04 09:52:16 +1100] [4638] [INFO] Worker exiting (pid: 4638)
alcali[4634]: [2020-12-04 09:52:16 +1100] [4640] [ERROR] Exception in worker process
alcali[4634]: Traceback (most recent call last):
alcali[4634]:   File "/opt/alcali/.venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
alcali[4634]:     worker.init_process()
alcali[4634]:   File "/opt/alcali/.venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
alcali[4634]:     self.load_wsgi()
alcali[4634]:   File "/opt/alcali/.venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
alcali[4634]:     self.wsgi = self.app.wsgi()
alcali[4634]:   File "/opt/alcali/.venv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
alcali[4634]:     self.callable = self.load()
alcali[4634]:   File "/opt/alcali/.venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
alcali[4634]:     return self.load_wsgiapp()
alcali[4634]:   File "/opt/alcali/.venv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
alcali[4634]:     return util.import_app(self.app_uri)
alcali[4634]:   File "/opt/alcali/.venv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
alcali[4634]:     mod = importlib.import_module(module)
alcali[4634]:   File "/opt/alcali/.venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
alcali[4634]:     return _bootstrap._gcd_import(name[level:], package, level)
alcali[4634]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
alcali[4634]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
alcali[4634]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
alcali[4634]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
alcali[4634]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
alcali[4634]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
alcali[4634]:   File "/opt/alcali/code/config/wsgi.py", line 16, in <module>
alcali[4634]:     application = get_wsgi_application()
alcali[4634]:   File "/opt/alcali/.venv/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
alcali[4634]:     django.setup(set_prefix=False)
alcali[4634]:   File "/opt/alcali/.venv/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
alcali[4634]:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
alcali[4634]:   File "/opt/alcali/.venv/lib/python3.7/site-packages/django/conf/__init__.py", line 83, in __getattr__
alcali[4634]:     self._setup(name)
alcali[4634]:   File "/opt/alcali/.venv/lib/python3.7/site-packages/django/conf/__init__.py", line 70, in _setup
alcali[4634]:     self._wrapped = Settings(settings_module)
alcali[4634]:   File "/opt/alcali/.venv/lib/python3.7/site-packages/django/conf/__init__.py", line 177, in __init__
alcali[4634]:     mod = importlib.import_module(self.SETTINGS_MODULE)
alcali[4634]:   File "/opt/alcali/.venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
alcali[4634]:     return _bootstrap._gcd_import(name[level:], package, level)
alcali[4634]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
alcali[4634]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
alcali[4634]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
alcali[4634]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
alcali[4634]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
alcali[4634]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
alcali[4634]:   File "/opt/alcali/code/config/settings.py", line 168, in <module>
alcali[4634]:     from .ldap_config import *
alcali[4634]:   File "/opt/alcali/code/config/ldap_config.py", line 2, in <module>
alcali[4634]:     import ldap
alcali[4634]: ModuleNotFoundError: No module named 'ldap'
```

The launch command is `/opt/alcali/.venv/bin/gunicorn config.wsgi:application --bind 0.0.0.0:8000 -w 4 -t 600` 

**Expected behavior**
Gunicorn should work like the dev server.

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Version `3000.1.0 with Salt 3002.2`

Thanks for this awesome project.

**Comment by valentin2105** [comment]
@pjanzen  Already installed, work on devserver, not with gunicorn..

**Comment by mattLLVW** [comment]
@valentin2105 i think it's because you installed from pip, i will release a new version soon.

**Comment by valentin2105** [comment]
@mattLLVW Hello,
I removed python-ldap from `pip3`  and `python3-ldap` is installed from apt. Same thing.

**Comment by mattLLVW** [comment]
you have to install dependencies **inside** the virtualenv created by the formula. 
Something like:

```bash
/opt/alcali/.venv/bin/activate
pip install --user alcali[ldap]
```
