### ISSUE TITLE
error : Run on Invalid Date ?!

### ISSUE THREAD

**Issue by pju51** [latenighttales/alcali#432]
Hello

I installed alcali in docker, it seemed to work because I can see the key salts, the minions, I can execute from alcali commands to the minions via the CLI, etc..

But after some tests, I found out that if I execute a command from a minion, I can't see the result on alcali because I always get the following error message: **Run on Invalid Date** (in the alcali logs, I have an error 500)
also if I refresh the functions, it doesn't work, I don't get them back.

it seems that : 
alkali -> minion OK
minion -> master-> alcali KO ("Run on Invalid Date" error)

my saltstack version is 3000.3. I tested alcali in version 3003.1 and 3000.1, same problem.

For the database, I had chosen mysql I installed the dependencies on my salt master (os: centos8) but i always had the following error "Returner 'alcali' does not support function prep_jid" when running the cmd : "salt-run saltutil.sync_all"
However "salt --versions-report" confirmed that the mysql client was present.

```
@salt-master-dc1-1 master.d]$ sudo salt-run saltutil.sync_all
[ERROR ] Returner 'alcali' does not support function prep_jid
[ERROR ] An un-handled exception was caught by salt's global exception handler:
KeyError: "Returner 'alcali' does not support function prep_jid"
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/salt/utils/job.py", line 60, in store_job
mminion.returners[jidstore_fstr](False, passed_jid=load['jid'])
File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1248, in __getitem__
func = super(LazyLoader, self).__getitem__(item)
File "/usr/lib/python3.6/site-packages/salt/utils/lazy.py", line 108, in __getitem__
raise KeyError(key)
KeyError: 'alcali.prep_jid'
```

I then switched to postgresql, and I didn't encounter any problem this time.

I've been using ntpd for time configuration, and I configured the docker-compose file to use the correct time, but the problem was still there

I noticed that even if the container is on time, there is still a several hours lag in the alkali logs, but it's at the application level so... I don't know if it's related to my problem.

What am I missing? Where is this error coming from?

screenshot:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/102222224/168559515-f21468cd-8475-465c-93d4-1742db46533a.png)

**Comment by pju51** [comment]
no news about my error :
status : views.JobDetail.failed
start time: Invalid Date

no idea what my problem might be?

**Comment by ggiesen** [comment]
I'm seeing this as well with Salt 3005
