### ISSUE TITLE
Issues configuring salt-api

### ISSUE THREAD

**Issue by ryan-dyer-sp** [latenighttales/alcali#48]
I appear to be having issues properly configuring the salt-api to use the alcali.py external auth.  After configuration when attempting to curl the salt-api I get issues.  I have tried user/pass as well as the token (from alcali manage_token).
```
(.venv) root@salt-master:/opt/alcali# curl -ski https://localhost:8080/login -H 'Accept: application/json' -d username='admin' -d password='password' -d eauth='alcali'
HTTP/1.1 401 Unauthorized
Content-Length: 1604
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/8.9.1
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Mon, 09 Sep 2019 15:45:02 GMT
Access-Control-Allow-Origin: *
Content-Type: text/html;charset=utf-8
Set-Cookie: session_id=10bcadeba634e3c66e45a1983f5df58aee9253aa; expires=Tue, 10 Sep 2019 01:45:02 GMT; Path=/

<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>Could not authenticate using provided credentials</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 858, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1877, in POST
    'Could not authenticate using provided credentials')
HTTPError: (401, 'Could not authenticate using provided credentials')
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 8.9.1</a>
      </span>
    </div>
    </body>
</html>
(.venv) root@salt-master:/opt/alcali# curl -ski https://localhost:8080/minions -H 'Accept: application/json' -H 'X-Auth-Token: <token>' -d client=local -d tgt='*' -d fun='test.ping'
HTTP/1.1 401 Unauthorized
Content-Length: 1037
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/8.9.1
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Mon, 09 Sep 2019 15:45:15 GMT
Access-Control-Allow-Origin: *
Content-Type: text/html;charset=utf-8
Set-Cookie: session_id=53b6c04c8534a46b68706ead23a896057543411f; expires=Tue, 10 Sep 2019 01:45:15 GMT; Path=/

<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>No permission -- see authorization schemes</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 661, in respond
    self.hooks.run('before_request_body')
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
HTTPError: (401, None)
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 8.9.1</a>
      </span>
    </div>
    </body>
</html>
```

The API has been configured as follows:
```
(.venv) root@salt-master:/etc/salt/master.d# ls
alcali.conf  auth.conf  ec2-tags.conf  file-roots.conf  salt-api.conf
(.venv) root@salt-master:/etc/salt/master.d# cat auth.conf
external_auth:
  alcali:
    admin:
      - .*
      - '@wheel'
      - '@runner'
      - '@jobs'

(.venv) root@salt-master:/etc/salt/master.d# cat salt-api.conf
rest_cherrypy:
  port: 8080
  host: 0.0.0.0
  debug: True
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key
(.venv) root@salt-master:/etc/salt/master.d# cat alcali.conf
event_return: [postgres]
master_job_cache: postgres
returner.postgres.host: 'dbhost'
returner.postgres.user: 'dbuser'
returner.postgres.passwd: 'dbpass'
returner.postgres.db: 'salt'
returner.postgres.port: 5432
(.venv) root@salt-master:/etc/salt/master.d# tail ../master
# to use OS defaults, typically 9 on Linux, see /proc/sys/net/ipv4/tcp_keepalive_probes.
#tcp_keepalive_cnt: -1

# How often, in seconds, to send keepalives after the first one. Default -1 to
# use OS defaults, typically 75 seconds on Linux, see
# /proc/sys/net/ipv4/tcp_keepalive_intvl.
#tcp_keepalive_intvl: -1

auth_dirs: [/srv/salt/auth]
```

Any assistance would be appreciated.

**Comment by mattLLVW** [comment]
Hi,
Thank you for your interest in Alcali. Please note that the current version is in Beta and there may be breaking changes in the final release.

On your issue, did you sync the modules on your master?

```bash
salt-run saltutil.sync_all
```
If it's the first time after putting the auth module in "/srv/salt/auth" it should return that it found the new module.

to curl the salt-api using alcali auth module, you should send the username you created in alcali, and the token as password.
If the auth fail, it should be logged in the master logs.

**Comment by ryan-dyer-sp** [comment]
```
> salt-run saltutil.sync_all
cache:
clouds:
engines:
fileserver:
grains:
modules:
output:
pillar:
proxymodules:
queues:
renderers:
returners:
runners:
sdb:
serializers:
states:
thorium:
tokens:
tops:
utils:
wheel:
```

**Comment by mattLLVW** [comment]
To add minions, you should first have keys in database.

To do so, you'll need to refresh keys using the FAB on the "keys" page.

**Comment by ryan-dyer-sp** [comment]
After refreshing keys and refreshing minions I now see things.  Are there plans on having this functionality automatically ran during app startup?  Or at least it should be added to the documentation for things you need to do to properly configure/install the app.

**Comment by mattLLVW** [comment]
There is a custom master returner that refresh keys automatically but we need to benchmark it properly.

I'm glad you manage to get it working.
