### ISSUE TITLE
Unexpected error while viewing conformity details

### ISSUE THREAD

**Issue by duhow** [latenighttales/alcali#505]
**Describe the bug**
Unexpected Django error appeared in logs and browser while viewing conformity details of a machine.

### 📝 Logs
<details>

```
Internal Server Error: /api/schedules/refresh/
Traceback (most recent call last):
  File "/opt/alcali/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/alcali/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/alcali/.local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/alcali/.local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/alcali/.local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/alcali/.local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/alcali/.local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/alcali/.local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/alcali/.local/lib/python3.9/site-packages/api/views/alcali.py", line 294, in refresh
    ret = refresh_schedules()
  File "/opt/alcali/.local/lib/python3.9/site-packages/api/backend/netapi.py", line 185, in refresh_schedules
    for job_name in minion_jobs:
TypeError: 'bool' object is not iterable
```

</details>

Version [3003.1.0](https://github.com/latenighttales/alcali/releases/tag/v3003.1.0)

**Comment by mattLLVW** [comment]
is it still the case with the last version?

**Comment by duhow** [comment]
Unable to reproduce again, just found it once...
